"""add incident_events

Revision ID: f02dc4f9f9bf
Revises: 
Create Date: 2026-01-16 16:19:14.093502

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f02dc4f9f9bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incident_transitions_action'), table_name='incident_transitions')
    op.drop_index(op.f('ix_incident_transitions_created_at'), table_name='incident_transitions')
    op.drop_index(op.f('ix_incident_transitions_drift_id'), table_name='incident_transitions')
    op.drop_index(op.f('ix_incident_transitions_from_state'), table_name='incident_transitions')
    op.drop_index(op.f('ix_incident_transitions_incident_id'), table_name='incident_transitions')
    op.drop_index(op.f('ix_incident_transitions_metric'), table_name='incident_transitions')
    op.drop_index(op.f('ix_incident_transitions_model_id'), table_name='incident_transitions')
    op.drop_index(op.f('ix_incident_transitions_org_id'), table_name='incident_transitions')
    op.drop_index(op.f('ix_incident_transitions_severity'), table_name='incident_transitions')
    op.drop_index(op.f('ix_incident_transitions_to_state'), table_name='incident_transitions')
    op.drop_table('incident_transitions')
    op.add_column('incidents', sa.Column('acknowledged_by_user_id', sa.Uuid(), nullable=True))
    op.add_column('incidents', sa.Column('acknowledged_at', sa.DateTime(), nullable=True))
    op.add_column('incidents', sa.Column('resolved_at', sa.DateTime(), nullable=True))
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'incidentseverity') THEN
                CREATE TYPE incidentseverity AS ENUM ('NONE', 'WARN', 'CRITICAL');
            END IF;
        END$$;
        """
    )
    op.execute(
        """
        ALTER TABLE incidents
        ALTER COLUMN severity TYPE incidentseverity
        USING (
            CASE
                WHEN severity IN ('critical', 'CRITICAL') THEN 'CRITICAL'
                WHEN severity IN ('warn', 'WARN') THEN 'WARN'
                WHEN severity IN ('none', 'NONE', 'ok', 'OK') THEN 'NONE'
                ELSE 'NONE'
            END
        )::incidentseverity
        """
    )
    op.create_index(op.f('ix_incidents_acknowledged_at'), 'incidents', ['acknowledged_at'], unique=False)
    op.create_index(op.f('ix_incidents_acknowledged_by_user_id'), 'incidents', ['acknowledged_by_user_id'], unique=False)
    op.create_index(op.f('ix_incidents_resolved_at'), 'incidents', ['resolved_at'], unique=False)
    inspector = sa.inspect(op.get_bind())
    if "incident_events" not in inspector.get_table_names():
        op.create_table(
            'incident_events',
            sa.Column('event_id', sa.Uuid(), nullable=False),
            sa.Column('incident_id', sa.Uuid(), nullable=False),
            sa.Column('org_id', sa.Uuid(), nullable=False),
            sa.Column('model_id', sa.String(), nullable=False),
            sa.Column('metric', sa.String(), nullable=False),
            sa.Column('ts', sa.DateTime(), nullable=False),
            sa.Column('action', sa.String(), nullable=False),
            sa.Column('prev_state', sa.String(), nullable=False),
            sa.Column('new_state', sa.String(), nullable=False),
            sa.Column('prev_severity', sa.String(), nullable=True),
            sa.Column('new_severity', sa.String(), nullable=True),
            sa.Column('value', sa.Float(), nullable=True),
            sa.Column('actor', sa.String(), nullable=False),
            sa.Column('actor_user_id', sa.Uuid(), nullable=True),
            sa.PrimaryKeyConstraint('event_id', name=op.f('incident_events_pkey'))
        )
        op.create_index(op.f('ix_incident_events_action'), 'incident_events', ['action'], unique=False)
        op.create_index(op.f('ix_incident_events_actor'), 'incident_events', ['actor'], unique=False)
        op.create_index(op.f('ix_incident_events_actor_user_id'), 'incident_events', ['actor_user_id'], unique=False)
        op.create_index(op.f('ix_incident_events_incident_id'), 'incident_events', ['incident_id'], unique=False)
        op.create_index(op.f('ix_incident_events_metric'), 'incident_events', ['metric'], unique=False)
        op.create_index(op.f('ix_incident_events_model_id'), 'incident_events', ['model_id'], unique=False)
        op.create_index(op.f('ix_incident_events_new_severity'), 'incident_events', ['new_severity'], unique=False)
        op.create_index(op.f('ix_incident_events_new_state'), 'incident_events', ['new_state'], unique=False)
        op.create_index(op.f('ix_incident_events_org_id'), 'incident_events', ['org_id'], unique=False)
        op.create_index(op.f('ix_incident_events_prev_severity'), 'incident_events', ['prev_severity'], unique=False)
        op.create_index(op.f('ix_incident_events_prev_state'), 'incident_events', ['prev_state'], unique=False)
        op.create_index(op.f('ix_incident_events_ts'), 'incident_events', ['ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incidents_resolved_at'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_acknowledged_by_user_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_acknowledged_at'), table_name='incidents')
    inspector = sa.inspect(op.get_bind())
    if "incident_events" in inspector.get_table_names():
        op.drop_index(op.f('ix_incident_events_ts'), table_name='incident_events')
        op.drop_index(op.f('ix_incident_events_prev_state'), table_name='incident_events')
        op.drop_index(op.f('ix_incident_events_prev_severity'), table_name='incident_events')
        op.drop_index(op.f('ix_incident_events_org_id'), table_name='incident_events')
        op.drop_index(op.f('ix_incident_events_new_state'), table_name='incident_events')
        op.drop_index(op.f('ix_incident_events_new_severity'), table_name='incident_events')
        op.drop_index(op.f('ix_incident_events_model_id'), table_name='incident_events')
        op.drop_index(op.f('ix_incident_events_metric'), table_name='incident_events')
        op.drop_index(op.f('ix_incident_events_incident_id'), table_name='incident_events')
        op.drop_index(op.f('ix_incident_events_actor_user_id'), table_name='incident_events')
        op.drop_index(op.f('ix_incident_events_actor'), table_name='incident_events')
        op.drop_index(op.f('ix_incident_events_action'), table_name='incident_events')
        op.drop_table('incident_events')
    op.execute(
        """
        ALTER TABLE incidents
        ALTER COLUMN severity TYPE VARCHAR
        USING severity::text
        """
    )
    op.drop_column('incidents', 'resolved_at')
    op.drop_column('incidents', 'acknowledged_at')
    op.drop_column('incidents', 'acknowledged_by_user_id')
    op.create_table('incident_transitions',
    sa.Column('transition_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('org_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('model_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('incident_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('from_state', postgresql.ENUM('NONE', 'WARN', 'CRITICAL', name='incidentstate'), autoincrement=False, nullable=False),
    sa.Column('to_state', postgresql.ENUM('NONE', 'WARN', 'CRITICAL', name='incidentstate'), autoincrement=False, nullable=False),
    sa.Column('action', postgresql.ENUM('NOOP', 'OPEN', 'ESCALATE', 'DOWNGRADE', 'UPDATE', 'RESOLVE', name='incidentaction'), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('metric', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('drift_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('transition_id', name=op.f('incident_transitions_pkey'))
    )
    op.create_index(op.f('ix_incident_transitions_to_state'), 'incident_transitions', ['to_state'], unique=False)
    op.create_index(op.f('ix_incident_transitions_severity'), 'incident_transitions', ['severity'], unique=False)
    op.create_index(op.f('ix_incident_transitions_org_id'), 'incident_transitions', ['org_id'], unique=False)
    op.create_index(op.f('ix_incident_transitions_model_id'), 'incident_transitions', ['model_id'], unique=False)
    op.create_index(op.f('ix_incident_transitions_metric'), 'incident_transitions', ['metric'], unique=False)
    op.create_index(op.f('ix_incident_transitions_incident_id'), 'incident_transitions', ['incident_id'], unique=False)
    op.create_index(op.f('ix_incident_transitions_from_state'), 'incident_transitions', ['from_state'], unique=False)
    op.create_index(op.f('ix_incident_transitions_drift_id'), 'incident_transitions', ['drift_id'], unique=False)
    op.create_index(op.f('ix_incident_transitions_created_at'), 'incident_transitions', ['created_at'], unique=False)
    op.create_index(op.f('ix_incident_transitions_action'), 'incident_transitions', ['action'], unique=False)
    # ### end Alembic commands ###
